# Generated by Django 5.1.4 on 2025-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectattachment_projectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
