# Generated by Django 5.1.4 on 2025-05-21 06:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_bio_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='dist/img/default-avatar.jpg', null=True, upload_to=accounts.models.profile_image_path_location),
        ),
    ]
