# Generated by Django 5.1.4 on 2025-05-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_assigned_to_task_last_updated_by_tasklink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_updated_by',
        ),
        migrations.DeleteModel(
            name='TaskLink',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
